Init
dice-group/sparql-transactional-test pull request #1
Opened 2023-09-07 06:36 UTC by Clueliss

2023-09-07 11:54 UTC, bigerl requested changes
I'll leave this one here already. For the rest, I am still busy reviewing.

2023-09-07 11:54 UTC, bigerl commented on generate_update_operations.sh
> +#!/bin/bash
I would really appreciate if we could do this in a modern, expressive language. Python, Kotlin, rust or even JS would be fine.

2023-09-07 11:54 UTC, bigerl commented on generate_update_operations.sh
> +        curl -X POST "$UPDATE_ENDPOINT_URL" -H 'Content-Type: application/sparql-update' -d "$op_str"
If I get this right, you don't manually calculate the expected result but use another triplestore (like fuseki) as reference.

2023-09-13 15:35 UTC, bigerl requested changes
Only a little nit-pick that is ATM not really relevant for Tentris. Otherwise, the rust code looks good.

2023-09-13 15:35 UTC, bigerl commented on src/update_worker.rs
> +            .query(&[("query", Self::make_verify_query(subject))])
th Accept header should be set to "application/n-triples" to ensure that the endpoint delivers the expected format.

2023-12-06 10:10 UTC, Clueliss commented on generate_update_operations.sh
> +#!/bin/bash
Will create an issue

2023-12-06 10:11 UTC, merged